name: patient-api-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api-clinica-medica
        run: mvn -B package --file pom.xml
      - name: Run Unit and Integration Tests
        working-directory: ./api-clinica-medica
        run: mvn test

  Acceptance:
    runs-on: ubuntu-latest
    needs: Commit
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Acceptance Tests
        working-directory: ./api-clinica-medica
        run: mvn test -Dtest=CucumberRunner
