name: patient-api-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        working-directory: ./api-clinica-medica
        run: mvn clean install
        
      - name: Run Unit and Integration Tests
        working-directory: ./api-clinica-medica
        run: mvn test

  Acceptance-Test:
    runs-on: ubuntu-latest
    needs: Commit
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Run Acceptance Tests
        working-directory: ./api-clinica-medica
        run: mvn test -Dtest=CucumberRunnerTest
  
  Deploy:
    runs-on: ubuntu-latest
    needs: [Commit, Acceptance-Test]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build Maven
        working-directory: ./api-clinica-medica
        run: mvn clean package
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./api-clinica-medica
          file: ./api-clinica-medica/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/patient-api:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/patient-api:latest
