name: patient-api-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api-clinica-medica
        run: mvn -B package --file pom.xml
      - name: Run Unit and Integration Tests
        working-directory: ./api-clinica-medica
        run: mvn test

  Acceptance-Test:
    runs-on: ubuntu-latest
    needs: Commit
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Acceptance Tests
        working-directory: ./api-clinica-medica
        run: mvn test -Dtest=CucumberRunnerTest
  
  Deploy-Docker:
    runs-on: ubuntu-latest
    needs: Acceptance-Test

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t patient-api:latest .
      - name: Tag Docker image
        run: docker tag patient-api:latest ${{ secrets.DOCKER_USERNAME }}/patient-api:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/patient-api:latest
      - name: Run Docker container
        run: docker run -d --name apiclinica -p 8080:8080 --hostname apiclinica ${{ secrets.DOCKER_USERNAME }}/patient-api:latest
